In [4]:
import tensorflow as tf

In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train /255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [8]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.12878902, -0.38364127,  0.15158519, -0.6175031 ,  0.03399685,
         0.01027078, -0.10761982, -0.5498901 , -0.17525779, -0.8788806 ]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.13710548, 0.08213139, 0.14026685, 0.06500462, 0.12470593,
        0.12178197, 0.108239  , 0.06955177, 0.10116003, 0.05005292]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.105523

In [14]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2950 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1403 - accuracy: 0.9590
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1055 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0866 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0750 - accuracy: 0.9768


In [16]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0742 - accuracy: 0.9787 - 894ms/epoch - 3ms/step


[0.07421687990427017, 0.9786999821662903]

In [17]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.90284305e-07, 9.14717646e-07, 8.62645393e-05, 8.38679611e-04,
        7.42978179e-11, 5.48764376e-07, 2.81686601e-11, 9.99070883e-01,
        4.90149432e-07, 1.91287677e-06],
       [2.20406676e-07, 4.09305030e-05, 9.99938726e-01, 1.00430270e-05,
        5.71053466e-16, 2.32504863e-06, 3.48103377e-08, 1.68271308e-13,
        7.73364627e-06, 3.12157591e-11],
       [1.71866517e-07, 9.99423027e-01, 8.46083349e-05, 3.07192422e-05,
        8.23921800e-06, 3.73799639e-06, 9.10322979e-06, 2.68918084e-04,
        1.71312204e-04, 2.60915016e-07],
       [9.99798357e-01, 3.26929328e-09, 2.16829885e-05, 2.87157445e-06,
        4.51078783e-08, 3.40958150e-06, 1.04446633e-04, 4.63250690e-05,
        2.73907830e-09, 2.30501610e-05],
       [2.57746842e-06, 9.45469258e-10, 2.67190762e-06, 1.31930449e-07,
        9.97370362e-01, 1.15241114e-07, 7.63326568e-07, 4.24847567e-05,
        1.63614322e-06, 2.57922313e-03]], dtype=float32)>